# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/hw_build.Vivado/uberclock.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/hw_build.Vivado/uberclock.cache/wt [current_project]
set_property parent.project_path /home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/hw_build.Vivado/uberclock.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/hw_build.Vivado/uberclock.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog /home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/sw_build/imem.INIT.vh
read_verilog -library xil_defaultlib -sv {
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/top.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/csr_build/generated-files/csr_pkg.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/3.build/csr_build/generated-files/csr.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/soc_if.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.cpu/soc_cpu.PICORV32.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/soc_fabric.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.cpu/cpu.PICORV32/picorv32.CHILI.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.cpu/cpu.PICORV32/picorv32_pcpi_mul.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.cpu/cpu.PICORV32/picorv32_pcpi_fast_mul.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.cpu/cpu.PICORV32/picorv32_pcpi_div.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.cpu/imem.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/soc_ram.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/soc_csr.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/uart.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/sync_fifo_ram.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/soc_pkg.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/ip.infra/clk_rst_gen.sv
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/fpgatech_lib/XILINX/fpga_pll_80M.sv
}
read_verilog -library xil_defaultlib {
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/dac/dac.v
  /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/adc/adc.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/constraints/top.xdc
set_property used_in_implementation false [get_files /home/nikola/Documents/GitHub/uberClock/3.miniac/1.hw/constraints/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a200tfbg484-2 -flatten_hierarchy none -verilog_define YOSYS
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
