// -------------------------------------------------------------
//
// Module: cic_comp_up
// Generated by MATLAB(R) 23.2 and Filter Design HDL Coder 23.2.
// Generated on: 2025-04-23 22:17:24
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// FIRAdderStyle: tree
// OptimizeForHDL: on
// EDAScriptGeneration: off
// AddPipelineRegisters: on
// Name: cic_comp_up
// TargetLanguage: Verilog
// TestBenchName: cic_comp_up_tb
// TestBenchStimulus: chirp 
// LoopUnrolling: on

// Filter Specifications:
//
// Sample Rate            : 40 kHz
// Response               : CIC Compensator
// Specification          : Fp,Fst,Ap,Ast
// Interpolation Factor   : 2
// Multirate Type         : Interpolator
// Passband Edge          : 5 kHz
// Stopband Atten.        : 70 dB
// Stopband Edge          : 8 kHz
// CIC Rate Change Factor : 1625
// Passband Ripple        : 1 dB
// Differential Delay     : 1
// Number of Sections     : 5
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// Folding Factor        : 1
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure      : Direct-Form FIR Polyphase Interpolator
// Interpolation Factor  : 2
// Polyphase Length      : 18
// Filter Length         : 36
// Stable                : Yes
// Linear Phase          : Yes (Type 2)
//
// Arithmetic            : fixed
// Numerator             : s16,15 -> [-1 1)
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module cic_comp_up
               (
                clk,
                clk_enable,
                reset,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   reset; 
  input   signed [15:0] filter_in; //sfix16_En15
  output  signed [15:0] filter_out; //sfix16_En15
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: cic_comp_up
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  parameter signed [15:0] coeffphase1_1 = 16'b0000000001000101; //sfix16_En15
  parameter signed [15:0] coeffphase1_2 = 16'b0000000100110100; //sfix16_En15
  parameter signed [15:0] coeffphase1_3 = 16'b1111111011000010; //sfix16_En15
  parameter signed [15:0] coeffphase1_4 = 16'b1111101011000011; //sfix16_En15
  parameter signed [15:0] coeffphase1_5 = 16'b0000001001100111; //sfix16_En15
  parameter signed [15:0] coeffphase1_6 = 16'b0000011011111011; //sfix16_En15
  parameter signed [15:0] coeffphase1_7 = 16'b1111001011111010; //sfix16_En15
  parameter signed [15:0] coeffphase1_8 = 16'b1111100100100000; //sfix16_En15
  parameter signed [15:0] coeffphase1_9 = 16'b0011011100111101; //sfix16_En15
  parameter signed [15:0] coeffphase1_10 = 16'b0100111010100010; //sfix16_En15
  parameter signed [15:0] coeffphase1_11 = 16'b0001010100011000; //sfix16_En15
  parameter signed [15:0] coeffphase1_12 = 16'b1110111000000100; //sfix16_En15
  parameter signed [15:0] coeffphase1_13 = 16'b1111111010101010; //sfix16_En15
  parameter signed [15:0] coeffphase1_14 = 16'b0000011101111100; //sfix16_En15
  parameter signed [15:0] coeffphase1_15 = 16'b1111110011110001; //sfix16_En15
  parameter signed [15:0] coeffphase1_16 = 16'b1111110000010011; //sfix16_En15
  parameter signed [15:0] coeffphase1_17 = 16'b0000000010110011; //sfix16_En15
  parameter signed [15:0] coeffphase1_18 = 16'b0000000011001011; //sfix16_En15
  parameter signed [15:0] coeffphase2_1 = 16'b0000000011001011; //sfix16_En15
  parameter signed [15:0] coeffphase2_2 = 16'b0000000010110011; //sfix16_En15
  parameter signed [15:0] coeffphase2_3 = 16'b1111110000010011; //sfix16_En15
  parameter signed [15:0] coeffphase2_4 = 16'b1111110011110001; //sfix16_En15
  parameter signed [15:0] coeffphase2_5 = 16'b0000011101111100; //sfix16_En15
  parameter signed [15:0] coeffphase2_6 = 16'b1111111010101010; //sfix16_En15
  parameter signed [15:0] coeffphase2_7 = 16'b1110111000000100; //sfix16_En15
  parameter signed [15:0] coeffphase2_8 = 16'b0001010100011000; //sfix16_En15
  parameter signed [15:0] coeffphase2_9 = 16'b0100111010100010; //sfix16_En15
  parameter signed [15:0] coeffphase2_10 = 16'b0011011100111101; //sfix16_En15
  parameter signed [15:0] coeffphase2_11 = 16'b1111100100100000; //sfix16_En15
  parameter signed [15:0] coeffphase2_12 = 16'b1111001011111010; //sfix16_En15
  parameter signed [15:0] coeffphase2_13 = 16'b0000011011111011; //sfix16_En15
  parameter signed [15:0] coeffphase2_14 = 16'b0000001001100111; //sfix16_En15
  parameter signed [15:0] coeffphase2_15 = 16'b1111101011000011; //sfix16_En15
  parameter signed [15:0] coeffphase2_16 = 16'b1111111011000010; //sfix16_En15
  parameter signed [15:0] coeffphase2_17 = 16'b0000000100110100; //sfix16_En15
  parameter signed [15:0] coeffphase2_18 = 16'b0000000001000101; //sfix16_En15

  // Signals
  reg  [1:0] cur_count; // ufix2
  wire phase_1; // boolean
  reg  signed [15:0] delay_pipeline [0:17] ; // sfix16_En15
  wire signed [31:0] product; // sfix32_En30
  wire signed [15:0] product_mux; // sfix16_En15
  wire signed [31:0] product_1; // sfix32_En30
  wire signed [15:0] product_mux_1; // sfix16_En15
  wire signed [31:0] product_2; // sfix32_En30
  wire signed [15:0] product_mux_2; // sfix16_En15
  wire signed [31:0] product_3; // sfix32_En30
  wire signed [15:0] product_mux_3; // sfix16_En15
  wire signed [31:0] product_4; // sfix32_En30
  wire signed [15:0] product_mux_4; // sfix16_En15
  wire signed [31:0] product_5; // sfix32_En30
  wire signed [15:0] product_mux_5; // sfix16_En15
  wire signed [31:0] product_6; // sfix32_En30
  wire signed [15:0] product_mux_6; // sfix16_En15
  wire signed [31:0] product_7; // sfix32_En30
  wire signed [15:0] product_mux_7; // sfix16_En15
  wire signed [31:0] product_8; // sfix32_En30
  wire signed [15:0] product_mux_8; // sfix16_En15
  wire signed [31:0] product_9; // sfix32_En30
  wire signed [15:0] product_mux_9; // sfix16_En15
  wire signed [31:0] product_10; // sfix32_En30
  wire signed [15:0] product_mux_10; // sfix16_En15
  wire signed [31:0] product_11; // sfix32_En30
  wire signed [15:0] product_mux_11; // sfix16_En15
  wire signed [31:0] product_12; // sfix32_En30
  wire signed [15:0] product_mux_12; // sfix16_En15
  wire signed [31:0] product_13; // sfix32_En30
  wire signed [15:0] product_mux_13; // sfix16_En15
  wire signed [31:0] product_14; // sfix32_En30
  wire signed [15:0] product_mux_14; // sfix16_En15
  wire signed [31:0] product_15; // sfix32_En30
  wire signed [15:0] product_mux_15; // sfix16_En15
  wire signed [31:0] product_16; // sfix32_En30
  wire signed [15:0] product_mux_16; // sfix16_En15
  wire signed [31:0] product_17; // sfix32_En30
  wire signed [15:0] product_mux_17; // sfix16_En15
  wire signed [36:0] sumvector1 [0:8] ; // sfix37_En30
  wire signed [31:0] add_signext; // sfix32_En30
  wire signed [31:0] add_signext_1; // sfix32_En30
  wire signed [32:0] add_temp; // sfix33_En30
  wire signed [31:0] add_signext_2; // sfix32_En30
  wire signed [31:0] add_signext_3; // sfix32_En30
  wire signed [32:0] add_temp_1; // sfix33_En30
  wire signed [31:0] add_signext_4; // sfix32_En30
  wire signed [31:0] add_signext_5; // sfix32_En30
  wire signed [32:0] add_temp_2; // sfix33_En30
  wire signed [31:0] add_signext_6; // sfix32_En30
  wire signed [31:0] add_signext_7; // sfix32_En30
  wire signed [32:0] add_temp_3; // sfix33_En30
  wire signed [31:0] add_signext_8; // sfix32_En30
  wire signed [31:0] add_signext_9; // sfix32_En30
  wire signed [32:0] add_temp_4; // sfix33_En30
  wire signed [31:0] add_signext_10; // sfix32_En30
  wire signed [31:0] add_signext_11; // sfix32_En30
  wire signed [32:0] add_temp_5; // sfix33_En30
  wire signed [31:0] add_signext_12; // sfix32_En30
  wire signed [31:0] add_signext_13; // sfix32_En30
  wire signed [32:0] add_temp_6; // sfix33_En30
  wire signed [31:0] add_signext_14; // sfix32_En30
  wire signed [31:0] add_signext_15; // sfix32_En30
  wire signed [32:0] add_temp_7; // sfix33_En30
  wire signed [31:0] add_signext_16; // sfix32_En30
  wire signed [31:0] add_signext_17; // sfix32_En30
  wire signed [32:0] add_temp_8; // sfix33_En30
  reg  signed [36:0] sumdelay_pipeline1 [0:8] ; // sfix37_En30
  wire signed [36:0] sumvector2 [0:4] ; // sfix37_En30
  wire signed [36:0] add_signext_18; // sfix37_En30
  wire signed [36:0] add_signext_19; // sfix37_En30
  wire signed [37:0] add_temp_9; // sfix38_En30
  wire signed [36:0] add_signext_20; // sfix37_En30
  wire signed [36:0] add_signext_21; // sfix37_En30
  wire signed [37:0] add_temp_10; // sfix38_En30
  wire signed [36:0] add_signext_22; // sfix37_En30
  wire signed [36:0] add_signext_23; // sfix37_En30
  wire signed [37:0] add_temp_11; // sfix38_En30
  wire signed [36:0] add_signext_24; // sfix37_En30
  wire signed [36:0] add_signext_25; // sfix37_En30
  wire signed [37:0] add_temp_12; // sfix38_En30
  reg  signed [36:0] sumdelay_pipeline2 [0:4] ; // sfix37_En30
  wire signed [36:0] sumvector3 [0:2] ; // sfix37_En30
  wire signed [36:0] add_signext_26; // sfix37_En30
  wire signed [36:0] add_signext_27; // sfix37_En30
  wire signed [37:0] add_temp_13; // sfix38_En30
  wire signed [36:0] add_signext_28; // sfix37_En30
  wire signed [36:0] add_signext_29; // sfix37_En30
  wire signed [37:0] add_temp_14; // sfix38_En30
  reg  signed [36:0] sumdelay_pipeline3 [0:2] ; // sfix37_En30
  wire signed [36:0] sumvector4 [0:1] ; // sfix37_En30
  wire signed [36:0] add_signext_30; // sfix37_En30
  wire signed [36:0] add_signext_31; // sfix37_En30
  wire signed [37:0] add_temp_15; // sfix38_En30
  reg  signed [36:0] sumdelay_pipeline4 [0:1] ; // sfix37_En30
  wire signed [36:0] sum5; // sfix37_En30
  wire signed [36:0] add_signext_32; // sfix37_En30
  wire signed [36:0] add_signext_33; // sfix37_En30
  wire signed [37:0] add_temp_16; // sfix38_En30
  wire signed [15:0] output_typeconvert; // sfix16_En15
  reg  signed [15:0] output_register; // sfix16_En15

  // Block Statements
  always @ (posedge clk or posedge reset)
    begin: ce_output
      if (reset == 1'b1) begin
        cur_count <= 2'b00;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 2'b01) begin
            cur_count <= 2'b00;
          end
          else begin
            cur_count <= cur_count + 2'b01;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 2'b01 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  //   ---------------- Delay Registers ----------------

  always @( posedge clk or posedge reset)
    begin: Delay_Pipeline_process
      if (reset == 1'b1) begin
        delay_pipeline[0] <= 0;
        delay_pipeline[1] <= 0;
        delay_pipeline[2] <= 0;
        delay_pipeline[3] <= 0;
        delay_pipeline[4] <= 0;
        delay_pipeline[5] <= 0;
        delay_pipeline[6] <= 0;
        delay_pipeline[7] <= 0;
        delay_pipeline[8] <= 0;
        delay_pipeline[9] <= 0;
        delay_pipeline[10] <= 0;
        delay_pipeline[11] <= 0;
        delay_pipeline[12] <= 0;
        delay_pipeline[13] <= 0;
        delay_pipeline[14] <= 0;
        delay_pipeline[15] <= 0;
        delay_pipeline[16] <= 0;
        delay_pipeline[17] <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          delay_pipeline[0] <= filter_in;
          delay_pipeline[1] <= delay_pipeline[0];
          delay_pipeline[2] <= delay_pipeline[1];
          delay_pipeline[3] <= delay_pipeline[2];
          delay_pipeline[4] <= delay_pipeline[3];
          delay_pipeline[5] <= delay_pipeline[4];
          delay_pipeline[6] <= delay_pipeline[5];
          delay_pipeline[7] <= delay_pipeline[6];
          delay_pipeline[8] <= delay_pipeline[7];
          delay_pipeline[9] <= delay_pipeline[8];
          delay_pipeline[10] <= delay_pipeline[9];
          delay_pipeline[11] <= delay_pipeline[10];
          delay_pipeline[12] <= delay_pipeline[11];
          delay_pipeline[13] <= delay_pipeline[12];
          delay_pipeline[14] <= delay_pipeline[13];
          delay_pipeline[15] <= delay_pipeline[14];
          delay_pipeline[16] <= delay_pipeline[15];
          delay_pipeline[17] <= delay_pipeline[16];
        end
      end
    end // Delay_Pipeline_process


  assign product_mux = (cur_count == 2'b00) ? coeffphase1_18 :
                      coeffphase2_18;
  assign product = delay_pipeline[17] * product_mux;

  assign product_mux_1 = (cur_count == 2'b00) ? coeffphase1_17 :
                        coeffphase2_17;
  assign product_1 = delay_pipeline[16] * product_mux_1;

  assign product_mux_2 = (cur_count == 2'b00) ? coeffphase1_16 :
                        coeffphase2_16;
  assign product_2 = delay_pipeline[15] * product_mux_2;

  assign product_mux_3 = (cur_count == 2'b00) ? coeffphase1_15 :
                        coeffphase2_15;
  assign product_3 = delay_pipeline[14] * product_mux_3;

  assign product_mux_4 = (cur_count == 2'b00) ? coeffphase1_14 :
                        coeffphase2_14;
  assign product_4 = delay_pipeline[13] * product_mux_4;

  assign product_mux_5 = (cur_count == 2'b00) ? coeffphase1_13 :
                        coeffphase2_13;
  assign product_5 = delay_pipeline[12] * product_mux_5;

  assign product_mux_6 = (cur_count == 2'b00) ? coeffphase1_12 :
                        coeffphase2_12;
  assign product_6 = delay_pipeline[11] * product_mux_6;

  assign product_mux_7 = (cur_count == 2'b00) ? coeffphase1_11 :
                        coeffphase2_11;
  assign product_7 = delay_pipeline[10] * product_mux_7;

  assign product_mux_8 = (cur_count == 2'b00) ? coeffphase1_10 :
                        coeffphase2_10;
  assign product_8 = delay_pipeline[9] * product_mux_8;

  assign product_mux_9 = (cur_count == 2'b00) ? coeffphase1_9 :
                        coeffphase2_9;
  assign product_9 = delay_pipeline[8] * product_mux_9;

  assign product_mux_10 = (cur_count == 2'b00) ? coeffphase1_8 :
                         coeffphase2_8;
  assign product_10 = delay_pipeline[7] * product_mux_10;

  assign product_mux_11 = (cur_count == 2'b00) ? coeffphase1_7 :
                         coeffphase2_7;
  assign product_11 = delay_pipeline[6] * product_mux_11;

  assign product_mux_12 = (cur_count == 2'b00) ? coeffphase1_6 :
                         coeffphase2_6;
  assign product_12 = delay_pipeline[5] * product_mux_12;

  assign product_mux_13 = (cur_count == 2'b00) ? coeffphase1_5 :
                         coeffphase2_5;
  assign product_13 = delay_pipeline[4] * product_mux_13;

  assign product_mux_14 = (cur_count == 2'b00) ? coeffphase1_4 :
                         coeffphase2_4;
  assign product_14 = delay_pipeline[3] * product_mux_14;

  assign product_mux_15 = (cur_count == 2'b00) ? coeffphase1_3 :
                         coeffphase2_3;
  assign product_15 = delay_pipeline[2] * product_mux_15;

  assign product_mux_16 = (cur_count == 2'b00) ? coeffphase1_2 :
                         coeffphase2_2;
  assign product_16 = delay_pipeline[1] * product_mux_16;

  assign product_mux_17 = (cur_count == 2'b00) ? coeffphase1_1 :
                         coeffphase2_1;
  assign product_17 = delay_pipeline[0] * product_mux_17;

  assign add_signext = product;
  assign add_signext_1 = product_1;
  assign add_temp = add_signext + add_signext_1;
  assign sumvector1[0] = $signed({{4{add_temp[32]}}, add_temp});

  assign add_signext_2 = product_2;
  assign add_signext_3 = product_3;
  assign add_temp_1 = add_signext_2 + add_signext_3;
  assign sumvector1[1] = $signed({{4{add_temp_1[32]}}, add_temp_1});

  assign add_signext_4 = product_4;
  assign add_signext_5 = product_5;
  assign add_temp_2 = add_signext_4 + add_signext_5;
  assign sumvector1[2] = $signed({{4{add_temp_2[32]}}, add_temp_2});

  assign add_signext_6 = product_6;
  assign add_signext_7 = product_7;
  assign add_temp_3 = add_signext_6 + add_signext_7;
  assign sumvector1[3] = $signed({{4{add_temp_3[32]}}, add_temp_3});

  assign add_signext_8 = product_8;
  assign add_signext_9 = product_9;
  assign add_temp_4 = add_signext_8 + add_signext_9;
  assign sumvector1[4] = $signed({{4{add_temp_4[32]}}, add_temp_4});

  assign add_signext_10 = product_10;
  assign add_signext_11 = product_11;
  assign add_temp_5 = add_signext_10 + add_signext_11;
  assign sumvector1[5] = $signed({{4{add_temp_5[32]}}, add_temp_5});

  assign add_signext_12 = product_12;
  assign add_signext_13 = product_13;
  assign add_temp_6 = add_signext_12 + add_signext_13;
  assign sumvector1[6] = $signed({{4{add_temp_6[32]}}, add_temp_6});

  assign add_signext_14 = product_14;
  assign add_signext_15 = product_15;
  assign add_temp_7 = add_signext_14 + add_signext_15;
  assign sumvector1[7] = $signed({{4{add_temp_7[32]}}, add_temp_7});

  assign add_signext_16 = product_16;
  assign add_signext_17 = product_17;
  assign add_temp_8 = add_signext_16 + add_signext_17;
  assign sumvector1[8] = $signed({{4{add_temp_8[32]}}, add_temp_8});

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process1
      if (reset == 1'b1) begin
        sumdelay_pipeline1[0] <= 0;
        sumdelay_pipeline1[1] <= 0;
        sumdelay_pipeline1[2] <= 0;
        sumdelay_pipeline1[3] <= 0;
        sumdelay_pipeline1[4] <= 0;
        sumdelay_pipeline1[5] <= 0;
        sumdelay_pipeline1[6] <= 0;
        sumdelay_pipeline1[7] <= 0;
        sumdelay_pipeline1[8] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumdelay_pipeline1[0] <= sumvector1[0];
          sumdelay_pipeline1[1] <= sumvector1[1];
          sumdelay_pipeline1[2] <= sumvector1[2];
          sumdelay_pipeline1[3] <= sumvector1[3];
          sumdelay_pipeline1[4] <= sumvector1[4];
          sumdelay_pipeline1[5] <= sumvector1[5];
          sumdelay_pipeline1[6] <= sumvector1[6];
          sumdelay_pipeline1[7] <= sumvector1[7];
          sumdelay_pipeline1[8] <= sumvector1[8];
        end
      end
    end // sumdelay_pipeline_process1

  assign add_signext_18 = sumdelay_pipeline1[0];
  assign add_signext_19 = sumdelay_pipeline1[1];
  assign add_temp_9 = add_signext_18 + add_signext_19;
  assign sumvector2[0] = (add_temp_9[37] == 1'b0 & add_temp_9[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_9[37] == 1'b1 && add_temp_9[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_9[36:0];

  assign add_signext_20 = sumdelay_pipeline1[2];
  assign add_signext_21 = sumdelay_pipeline1[3];
  assign add_temp_10 = add_signext_20 + add_signext_21;
  assign sumvector2[1] = (add_temp_10[37] == 1'b0 & add_temp_10[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_10[37] == 1'b1 && add_temp_10[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_10[36:0];

  assign add_signext_22 = sumdelay_pipeline1[4];
  assign add_signext_23 = sumdelay_pipeline1[5];
  assign add_temp_11 = add_signext_22 + add_signext_23;
  assign sumvector2[2] = (add_temp_11[37] == 1'b0 & add_temp_11[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_11[37] == 1'b1 && add_temp_11[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_11[36:0];

  assign add_signext_24 = sumdelay_pipeline1[6];
  assign add_signext_25 = sumdelay_pipeline1[7];
  assign add_temp_12 = add_signext_24 + add_signext_25;
  assign sumvector2[3] = (add_temp_12[37] == 1'b0 & add_temp_12[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_12[37] == 1'b1 && add_temp_12[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_12[36:0];

  assign sumvector2[4] = sumdelay_pipeline1[8];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process2
      if (reset == 1'b1) begin
        sumdelay_pipeline2[0] <= 0;
        sumdelay_pipeline2[1] <= 0;
        sumdelay_pipeline2[2] <= 0;
        sumdelay_pipeline2[3] <= 0;
        sumdelay_pipeline2[4] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumdelay_pipeline2[0] <= sumvector2[0];
          sumdelay_pipeline2[1] <= sumvector2[1];
          sumdelay_pipeline2[2] <= sumvector2[2];
          sumdelay_pipeline2[3] <= sumvector2[3];
          sumdelay_pipeline2[4] <= sumvector2[4];
        end
      end
    end // sumdelay_pipeline_process2

  assign add_signext_26 = sumdelay_pipeline2[0];
  assign add_signext_27 = sumdelay_pipeline2[1];
  assign add_temp_13 = add_signext_26 + add_signext_27;
  assign sumvector3[0] = (add_temp_13[37] == 1'b0 & add_temp_13[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_13[37] == 1'b1 && add_temp_13[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_13[36:0];

  assign add_signext_28 = sumdelay_pipeline2[2];
  assign add_signext_29 = sumdelay_pipeline2[3];
  assign add_temp_14 = add_signext_28 + add_signext_29;
  assign sumvector3[1] = (add_temp_14[37] == 1'b0 & add_temp_14[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_14[37] == 1'b1 && add_temp_14[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_14[36:0];

  assign sumvector3[2] = sumdelay_pipeline2[4];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process3
      if (reset == 1'b1) begin
        sumdelay_pipeline3[0] <= 0;
        sumdelay_pipeline3[1] <= 0;
        sumdelay_pipeline3[2] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumdelay_pipeline3[0] <= sumvector3[0];
          sumdelay_pipeline3[1] <= sumvector3[1];
          sumdelay_pipeline3[2] <= sumvector3[2];
        end
      end
    end // sumdelay_pipeline_process3

  assign add_signext_30 = sumdelay_pipeline3[0];
  assign add_signext_31 = sumdelay_pipeline3[1];
  assign add_temp_15 = add_signext_30 + add_signext_31;
  assign sumvector4[0] = (add_temp_15[37] == 1'b0 & add_temp_15[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_15[37] == 1'b1 && add_temp_15[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_15[36:0];

  assign sumvector4[1] = sumdelay_pipeline3[2];

  always @ (posedge clk or posedge reset)
    begin: sumdelay_pipeline_process4
      if (reset == 1'b1) begin
        sumdelay_pipeline4[0] <= 0;
        sumdelay_pipeline4[1] <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          sumdelay_pipeline4[0] <= sumvector4[0];
          sumdelay_pipeline4[1] <= sumvector4[1];
        end
      end
    end // sumdelay_pipeline_process4

  assign add_signext_32 = sumdelay_pipeline4[0];
  assign add_signext_33 = sumdelay_pipeline4[1];
  assign add_temp_16 = add_signext_32 + add_signext_33;
  assign sum5 = (add_temp_16[37] == 1'b0 & add_temp_16[36] != 1'b0) ? 37'b0111111111111111111111111111111111111 : 
      (add_temp_16[37] == 1'b1 && add_temp_16[36] != 1'b1) ? 37'b1000000000000000000000000000000000000 : add_temp_16[36:0];

  assign output_typeconvert = (sum5[36] == 1'b0 & sum5[35:30] != 6'b000000) ? 16'b0111111111111111 : 
      (sum5[36] == 1'b1 && sum5[35:30] != 6'b111111) ? 16'b1000000000000000 : $signed({1'b0, sum5[30:15]} + (sum5[36] & |sum5[14:0]));

  always @ (posedge clk or posedge reset)
    begin: Output_Register_process
      if (reset == 1'b1) begin
        output_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          output_register <= output_typeconvert;
        end
      end
    end // Output_Register_process

  // Assignment Statements
  assign ce_out = phase_1;
  assign filter_out = output_register;
endmodule  // cic_comp_up
