#ifndef UBERCLOCK_CONFIG_H
#define UBERCLOCK_CONFIG_H

#include <stdint.h>

#ifndef UBERCLOCK_CHANNEL_COUNT
#define UBERCLOCK_CHANNEL_COUNT 5u
#endif

#define UBERCLOCK_FFT_MAX_N 2048u
#define UBERCLOCK_FFT_CFG_MAX_BYTES 32768u

#define UBERCLOCK_TRACK_RF_FS_HZ            65000000u
#define UBERCLOCK_TRACK_DEFAULT_STEP_HZ     5u
#define UBERCLOCK_TRACK_DEFAULT_MAX_STEPS   400u
#define UBERCLOCK_TRACK_DEFAULT_N           2048u
#define UBERCLOCK_TRACK_DEFAULT_SETTLE      256u
#define UBERCLOCK_TRACK_DEFAULT_CENTER_HZ   1000u
#define UBERCLOCK_TRACK_DEFAULT_DELTA_HZ    30u
#define UBERCLOCK_TRACK_DEFAULT_BAND_BINS   1u
#define UBERCLOCK_TRACK_STEP_WAIT_TICKS     10000u
#define UBERCLOCK_TRACK_INTERVAL_TICKS      10000u
#define UBERCLOCK_TRACK_CORR_SHIFT          10u
#define UBERCLOCK_TRACK_MAX_STEP_HZ         2
#define UBERCLOCK_TRACK_ERR_ALPHA_NUM       1
#define UBERCLOCK_TRACK_ERR_ALPHA_DEN       4
#define UBERCLOCK_TRACK_KP_NUM              1
#define UBERCLOCK_TRACK_KP_DEN              4
#define UBERCLOCK_TRACK_MIN_CONF_PCT        5u
#define UBERCLOCK_TRACK_WEAK_DEADBAND_PCT   10u
#define UBERCLOCK_TRACK_WEAK_GAIN_DEN       4
#define UBERCLOCK_TRACK_WEAK_MAX_ERR_MHZ    750
#define UBERCLOCK_TRACK_BG_SERVICE_PERIOD   16u
#define UBERCLOCK_TRACK_FIFO_WAIT_POLLS     1000000u
#define UBERCLOCK_TRACK_SIDE_MIN_PCT        2u
#define UBERCLOCK_TRACK_SIDE_MAX_PCT        95u
#define UBERCLOCK_TRACK_SIDE_BALANCE_PCT    40u

#define UBERCLOCK_CAPTURE_SAMPLE_COUNT 2048u

#endif
